export const IS_LOGIN = 'IS_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const TRY_LOGIN = 'TRY_LOGIN'

export const SAVE_USER_DATA = 'SAVE_USER_DATA'

export const IS_LOGIN_MODAL_OPEN = 'IS_LOGIN_MODAL_OPEN'
export const LOGIN_MODAL_OPEN = 'LOGIN_MODAL_OPEN'
export const LOGIN_MODAL_CLOSE = 'LOGIN_MODAL_CLOSE'

export const REQUEST_LOGIN_MODAL_OPEN = 'REQUEST_LOGIN_MODAL_OPEN'
export const REQUEST_LOGIN_MODAL_CLOSE = 'REQUEST_LOGIN_MODAL_CLOSE'

export const SAVE_TOKEN = 'SAVE_TOKEN'


