export const IS_LOGIN = 'IS_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const TRY_LOGIN = 'TRY_LOGIN'

export const SIGN_UP_USER = 'SIGN_UP_USER'
export const LOG_OUT_USER = 'LOG_OUT_USER'

export const SAVE_USER_DATA = 'SAVE_USER_DATA'

export const IS_LOGIN_MODAL_OPEN = 'IS_LOGIN_MODAL_OPEN'
export const LOGIN_MODAL_OPEN = 'LOGIN_MODAL_OPEN'
export const LOGIN_MODAL_CLOSE = 'LOGIN_MODAL_CLOSE'

export const REQUEST_LOGIN_MODAL_OPEN = 'REQUEST_LOGIN_MODAL_OPEN'
export const REQUEST_LOGIN_MODAL_CLOSE = 'REQUEST_LOGIN_MODAL_CLOSE'

export const ASK_NONE_SAVE_MODAL_OPEN = 'ASK_NONE_SAVE_MODAL_OPEN'
export const ASK_NONE_SAVE_MODAL_CLOSE = 'ASK_NONE_SAVE_MODAL_CLOSE'

export const CREATE_ERROR_MODAL_OPEN = 'CREATE_ERROR_MODAL_OPEN'
export const CREATE_ERROR_MODAL_CLOSE = 'CREATE_ERROR_MODAL_CLOSE'

export const CREATE_SUCCESS_MODAL_OPEN = 'CREATE_SUCCESS_MODAL_OPEN'
export const CREATE_SUCCESS_MODAL_CLOSE = 'CREATE_SUCCESS_MODAL_CLOSE'

export const CREATE_NEW_ACCOUNT_MODAL_OPEN = "CREATE_NEW_ACCOUNT_MODAL_OPEN"
export const CREATE_NEW_ACCOUNT_MODAL_CLOSE = "CREATE_NEW_ACCOUNT_MODAL_CLOSE"

export const GET_USERNOW_GROUP = "GET_USERNOW_GROUP"

export const CREATE_NEW_ACCOUNT = "CREATE_NEW_ACCOUT"




