export const IS_LOGIN = 'IS_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const TRY_LOGIN = 'TRY_LOGIN'
export const TRY_GOOGLE_LOGIN = 'TRY_GOOGLE_LOGIN'
export const SAVE_USER_GOOGLE = 'SAVE_USER_GOOGLE'

export const SIGN_UP_USER = 'SIGN_UP_USER'
export const LOG_OUT_USER = 'LOG_OUT_USER'
export const SIGN_OUT_USER = 'SIGN_OUT_USER'
export const SAVE_USER_DATA = 'SAVE_USER_DATA'

export const IS_LOGIN_MODAL_OPEN = 'IS_LOGIN_MODAL_OPEN'
export const LOGIN_MODAL_OPEN = 'LOGIN_MODAL_OPEN'
export const LOGIN_MODAL_CLOSE = 'LOGIN_MODAL_CLOSE'

export const REQUEST_LOGIN_MODAL_OPEN = 'REQUEST_LOGIN_MODAL_OPEN'
export const REQUEST_LOGIN_MODAL_CLOSE = 'REQUEST_LOGIN_MODAL_CLOSE'

export const ASK_NONE_SAVE_MODAL_OPEN = 'ASK_NONE_SAVE_MODAL_OPEN'
export const ASK_NONE_SAVE_MODAL_CLOSE = 'ASK_NONE_SAVE_MODAL_CLOSE'

export const CREATE_ERROR_MODAL_OPEN = 'CREATE_ERROR_MODAL_OPEN'
export const CREATE_ERROR_MODAL_CLOSE = 'CREATE_ERROR_MODAL_CLOSE'

export const CREATE_SUCCESS_MODAL_OPEN = 'CREATE_SUCCESS_MODAL_OPEN'
export const CREATE_SUCCESS_MODAL_CLOSE = 'CREATE_SUCCESS_MODAL_CLOSE'

export const CREATE_NEW_ACCOUNT_MODAL_OPEN = "CREATE_NEW_ACCOUNT_MODAL_OPEN"
export const CREATE_NEW_ACCOUNT_MODAL_CLOSE = "CREATE_NEW_ACCOUNT_MODAL_CLOSE"

export const GET_USERNOW_GROUP = "GET_USERNOW_GROUP"

export const CREATE_NEW_ACCOUNT = "CREATE_NEW_ACCOUT"
export const CREATE_NEW_ACCOUNT_ERR = "CREATE_NEW_ACCOUNT_ERR"

export const LOADING_WORKER_START = "LOADING_WORKER_START"
export const NOW_LOADING_ON = "NOW_LOADING_ON"
export const NOW_LOADING_OFF = "NOW_LOADING_OFf"

export const ADD_MEMBER_MODAL_OPEN = "ADD_MEMBER_MODAL_OPEN"
export const ADD_MEMBER_MODAL_CLOSE = "ADD_MEMBER_MODAL_CLOSE"

export const ADD_MEMEBER_WORKER_START = "ADD_MEMEBER_WORKER_START"
export const ADD_MEMBER_ERR = "ADD_MEMBER_ERR"

export const CREATE_NEW_CONTENT = "CREATE_NEW_CONTENT"

export const UPDATE_GROUP_MODAL_OPEN = 'UPDATE_GROUP_MODAL_OPEN'
export const UPDATE_GROUP_MODAL_CLOSE ='UPDATE_GROUP_MODAL_CLOSE'

export const UPDATE_GROUP_TOTAL_COST = "UPDATE_GROUP_TOTAL_COST"

export const DELETE_ACCOUNT = "DELETE_ACCOUNT"

export const CHANGE_DETAIL_DATE = "CHANGE_DETAIL_DATE"

export const GET_USER_DATA_AGAIN = "GET_USER_DATA_AGAIN"

export const UPDATE_CONTENT_MODAL_OPEN = "UPDATE_CONTENT_MODAL_OPEN"
export const UPDATE_CONTENT_MODAL_CLOSE = "UPDATE_CONTENT_MODAL_CLOSE"
export const UPDATE_CONTENT = "UPDATE_CONTENT"
export const DELETE_CONTENT = "DELETE_CONTENT"

export const SEND_EMAIL_MODAL_OPEN = "SEND_EMAIL_MODAL_OPEN"
export const SEND_EMAIL_MODAL_CLOSE = "SEND_EMAIL_MODAL_CLOSE"
export const SEND_EMAIL = "SEND_EMAIL"

export const OUT_OF_ACCOUNT = "OUT_OF_ACCOUNT"
export const OUT_OF_ACCOUNT_MODAL_OPEN = "OUT_OF_ACCOUNT_MODAL_OPEN"
export const OUT_OF_ACCOUNT_MODAL_CLOSE = "OUT_OF_ACCOUNT_MODAL_CLOSE"

export const OUT_OF_USER = "OUT_OF_USER"
export const OUT_OF_USER_MODAL_OPEN = "OUT_OF_USER_MODAL_OPEN"
export const OUT_OF_USER_MODAL_CLOSE = "OUT_OF_USER_MODAL_CLOSE"

export const SEE_DETAIL_MODAL_OPEN = "SEE_DETAIL_MODAL_OPEN"
export const SEE_DETAIL_MODAL_CLOSE = "SEE_DETAIL_MODAL_CLOSE"







